### ISSUE TITLE
SDL2 support

### ISSUE THREAD

**Issue by vit1251** [singpolyma/st-sdl#1]
Hello work under SDL2 support here https://github.com/vit1251/st-sdl and welcome an contribution and feedback
Have you plan to continue develop and work with pull requests on SDL2?

**Comment by singpolyma** [comment]
I haven't looked at this in awhile because it was an experiment for BB10 at the time, but happen to take PRs or other feedback if you find this useful.

**Comment by vit1251** [comment]
OK. Thanks.

**Comment by barracuda156** [comment]
@singpolyma Maybe re-open this? It will be nice to have SDL2 support.
